using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace FolderOrganizer;

public static class IconAliases
{
    // Manual overrides for extensions that don't match icon names directly
    private static readonly Dictionary<string, string> ManualOverrides =
        new(StringComparer.OrdinalIgnoreCase)
    {
        // Multiple extensions mapping to one icon
        ["mdb"] = "access",
        ["accdb"] = "access",
        ["as"] = "actionscript",
        ["scpt"] = "applescript",
        ["ino"] = "arduino",
        ["asm"] = "assembly",
        ["ahk"] = "autohotkey",
        ["au3"] = "autoit",
        ["fla"] = "flash",
        ["h"] = "cheader",
        ["hpp"] = "cppheader",
        ["hxx"] = "cppheader",
        ["hh"] = "cppheader",
        ["jsx"] = "reactjs",
        ["tsx"] = "reactts",
        ["jsonc"] = "json",
        ["pyw"] = "python",
        ["pyi"] = "python",
        ["pyc"] = "python",
        ["pyd"] = "python",
        ["pyo"] = "python",
        ["rbw"] = "ruby",
        ["kt"] = "kotlin",
        ["kts"] = "kotlin",
        ["dart"] = "dartlang",
        ["htm"] = "html",
        ["phtml"] = "php",
        ["php3"] = "php",
        ["php4"] = "php",
        ["php5"] = "php",
        ["php7"] = "php",
        ["phps"] = "php",
        ["rbw"] = "ruby",
        ["mjs"] = "js",
        ["cjs"] = "js",
        ["mts"] = "typescript",
        ["cts"] = "typescript",
        ["m4a"] = "audio",
        ["wma"] = "audio",
        ["alac"] = "audio",
        ["webm"] = "video",
        ["mkv"] = "video",
        ["m4v"] = "video",
        ["3gp"] = "video",
        ["mpg"] = "video",
        ["mpeg"] = "video",
        ["rar"] = "zip",
        ["7z"] = "zip",
        ["tar"] = "zip",
        ["gz"] = "zip",
        ["bz2"] = "zip",
        ["xz"] = "zip",
        ["tgz"] = "zip",
        ["cxx"] = "cpp",
        ["cc"] = "cpp",
        ["csx"] = "csharp",
        ["war"] = "jar",
        ["ear"] = "jar",
        ["phtml"] = "php",
        ["rake"] = "rake",
        ["gem"] = "ruby",
        ["gemspec"] = "ruby",
        ["toml"] = "toml",
        ["mdown"] = "markdown",
        ["mkdn"] = "markdown",
        ["mkd"] = "markdown",
        ["mdwn"] = "markdown",
        ["mdtxt"] = "markdown",
        ["mdtext"] = "markdown",
        ["sqlite3"] = "sqlite",
        ["db3"] = "db",
        ["bash"] = "shell",
        ["zsh"] = "shell",
        ["fish"] = "shell",
        ["cmd"] = "bat",
        ["psm1"] = "powershell_psm",
        ["psd1"] = "powershell_psd",
        ["ps1xml"] = "powershell",
        ["node"] = "node",
        ["nvmrc"] = "node",
        ["npmignore"] = "npm",
        ["npmrc"] = "npm",
        ["yarnrc"] = "yarn",
        ["bowerrc"] = "bower",
        ["webpack"] = "webpack",
        ["babelrc"] = "babel",
        ["eslintrc"] = "eslint",
        ["eslintrc.js"] = "eslint",
        ["eslintrc.json"] = "eslint",
        ["eslintrc.yaml"] = "eslint",
        ["eslintrc.yml"] = "eslint",
        ["eslintignore"] = "eslint",
        ["prettierrc"] = "prettier",
        ["prettier.config.js"] = "prettier",
        ["prettierignore"] = "prettier",
        ["tsconfig.json"] = "tsconfig",
        ["tsconfig"] = "tsconfig",
        ["angular-cli.json"] = "angular",
        ["angular.json"] = "angular",
        ["xls"] = "excel",
        ["xlsx"] = "excel",
        ["xlsm"] = "excel",
        ["xlsb"] = "excel",
        ["csv"] = "excel",
        ["doc"] = "word",
        ["docx"] = "word",
        ["docm"] = "word",
        ["dot"] = "word",
        ["dotx"] = "word",
        ["dotm"] = "word",
        ["ppt"] = "powerpoint",
        ["pptx"] = "powerpoint",
        ["pptm"] = "powerpoint",
        ["pps"] = "powerpoint",
        ["ppsx"] = "powerpoint",
        ["ppsm"] = "powerpoint",
        ["pot"] = "powerpoint",
        ["potx"] = "powerpoint",
        ["potm"] = "powerpoint",
        ["msg"] = "outlook",
        ["pst"] = "outlook",
        ["ost"] = "outlook",
        ["one"] = "onenote",
        ["onetoc2"] = "onenote",
        ["psd"] = "photoshop",
        ["psb"] = "photoshop",
        ["indd"] = "adobe",
        ["indt"] = "adobe",
        ["prproj"] = "adobe",
        ["aep"] = "adobe",
        ["dwt"] = "adobe",
        ["swf"] = "flash",
        ["blend"] = "blender",
        ["fbx"] = "fbx",
        ["obj"] = "binary",
        ["stl"] = "binary",
        ["gltf"] = "gltf",
        ["glb"] = "gltf",
        ["dwg"] = "drawio",
        ["dxf"] = "drawio",
        ["skp"] = "sketch",
        ["bib"] = "tex",
        ["sty"] = "tex",
        ["cls"] = "tex",
        ["mat"] = "matlab",
        ["fig"] = "matlab",
        ["clj"] = "clojure",
        ["cljs"] = "clojurescript",
        ["cljc"] = "clojure",
        ["edn"] = "clojure",
        ["ex"] = "elixir",
        ["exs"] = "elixir",
        ["erl"] = "erlang",
        ["hrl"] = "erlang",
        ["fs"] = "fsharp",
        ["fsi"] = "fsharp",
        ["fsx"] = "fsharp",
        ["fsscript"] = "fsharp",
        ["vba"] = "vba",
        ["vbhtml"] = "vbhtml",
        ["vbproj"] = "vbproj",
        ["csh"] = "shell",
        ["tcsh"] = "shell",
        ["ksh"] = "shell",
        ["mk"] = "make",
        ["mak"] = "make",
        ["cmake"] = "cmake",
        ["cmakelists.txt"] = "cmake",
        ["ctest"] = "cmake",
        ["gradlew"] = "gradle",
        ["pom.xml"] = "maven",
        ["mvn"] = "maven",
        ["build.xml"] = "ant",
        ["nupkg"] = "nuget",
        ["nuspec"] = "nuget",
        ["composer.json"] = "composer",
        ["composer.lock"] = "composer",
        ["requirements.txt"] = "pip",
        ["pipfile"] = "pip",
        ["pipfile.lock"] = "pip",
        ["pyproject.toml"] = "poetry",
        ["poetry.lock"] = "poetry",
        ["cargo.toml"] = "cargo",
        ["cargo.lock"] = "cargo",
        ["go.mod"] = "go",
        ["go.sum"] = "go",
        ["package.json"] = "npm",
        ["package-lock.json"] = "npm",
        ["yarn.lock"] = "yarn",
        ["bower.json"] = "bower",
        ["ashx"] = "aspx",
        ["asmx"] = "aspx",
        ["svc"] = "aspx",
        ["axd"] = "aspx",
        ["cfm"] = "cfm",
        ["cfc"] = "cfc",
        ["tf"] = "terraform",
        ["tfvars"] = "terraform",
        ["hcl"] = "terraform",
        ["vagrantfile"] = "vagrant",
        ["docker-compose.yml"] = "docker",
        ["docker-compose.yaml"] = "docker",
        ["travis.yml"] = "travis",
        ["gitlab-ci.yml"] = "gitlab",
        ["circleci"] = "circleci",
        ["jenkinsfile"] = "jenkins",
        ["azure-pipelines.yml"] = "azurepipelines",
        ["appveyor.yml"] = "appveyor",
        ["gql"] = "graphql",
        ["graphql"] = "graphql",
        ["proto"] = "protobuf",
        ["avsc"] = "avro",
        ["avdl"] = "avro",
        ["avpr"] = "avro",
        ["thrift"] = "binary",
        ["swagger.json"] = "swagger",
        ["swagger.yaml"] = "swagger",
        ["openapi.json"] = "swagger",
        ["openapi.yaml"] = "swagger",
        ["postman.json"] = "postman",
        ["insomnia.json"] = "postman",
        ["prisma"] = "prisma",
        ["gitignore"] = "git",
        ["gitattributes"] = "git",
        ["gitmodules"] = "git",
        ["gitkeep"] = "git",
        ["git-blame-ignore-revs"] = "git",
        ["svn"] = "subversion",
        ["hg"] = "mercurial",
        ["bzr"] = "bazaar",
        ["fossil"] = "fossil",
        ["cvs"] = "cvs",
        ["editorconfig"] = "editorconfig",
        ["idea"] = "idea",
        ["vscode"] = "vscode",
        ["vscodeignore"] = "vscode",
        ["code-workspace"] = "vscode",
        ["makefile"] = "make",
        ["rakefile"] = "rake",
        ["gulpfile"] = "gulp",
        ["gruntfile"] = "grunt",
        ["webpackfile"] = "webpack",
        ["rollup.config.js"] = "rollup",
        ["spec.js"] = "test",
        ["spec.ts"] = "test",
        ["test.js"] = "test",
        ["test.ts"] = "test",
        ["jest.config.js"] = "jest",
        ["jasmine.json"] = "jasmine",
        ["mocha.opts"] = "mocha",
        ["readme"] = "markdown",
        ["changelog"] = "markdown",
        ["contributing"] = "markdown",
        ["authors"] = "markdown",
        ["todo"] = "todo",
        ["conf"] = "config",
        ["cfg"] = "config",
        ["lock"] = "lock",
        ["backup"] = "bak",
        ["old"] = "bak",
        ["tmp"] = "temp",
        ["temp"] = "temp",
        ["dat"] = "binary",
        ["data"] = "binary",
        ["bin"] = "binary",
        ["ttf"] = "font",
        ["otf"] = "font",
        ["woff"] = "font",
        ["woff2"] = "font",
        ["eot"] = "font",
        ["cer"] = "cert",
        ["crt"] = "cert",
        ["pem"] = "cert",
        ["p12"] = "cert",
        ["pfx"] = "cert",
        ["pub"] = "key",
        ["asc"] = "key",
        ["gpg"] = "gpg",
        ["ppk"] = "key",
        ["schema"] = "db",
        ["ddl"] = "sql",
        ["migration"] = "sql",
        ["migrate"] = "sql",
        ["seed"] = "sql",
        ["seeds"] = "sql",
        ["fixture"] = "test",
        ["fixtures"] = "test",
        ["rst"] = "text",
        ["rtf"] = "text",
        ["nfo"] = "text",
        ["tsv"] = "excel",
        ["odt"] = "libreoffice_writer",
        ["ods"] = "libreoffice_calc",
        ["odp"] = "libreoffice_impress",
        ["odg"] = "libreoffice_draw",
        ["odb"] = "libreoffice_base",
        ["pages"] = "publisher",
        ["numbers"] = "excel",
        ["mobi"] = "epub",
        ["azw"] = "epub",
        ["azw3"] = "epub",
        ["cbz"] = "epub",
        ["cbr"] = "epub",
        ["cb7"] = "epub",
        ["cbt"] = "epub",
        ["mtl"] = "text",
        ["max"] = "maya",
        ["ma"] = "maya",
        ["mb"] = "maya",
        ["unity"] = "unity",
        ["unity3d"] = "unity",
        ["prefab"] = "unity",
        ["asset"] = "asset",
        ["meta"] = "asset",
        ["tscn"] = "tscn",
        ["tres"] = "tres",
        ["gd"] = "gdscript",
        ["uasset"] = "binary",
        ["umap"] = "binary",
        ["upk"] = "binary",
        ["map"] = "map",
        ["jsmap"] = "jsmap",
        ["cssmap"] = "cssmap",
        ["xhtml"] = "html",
        ["styl"] = "stylus",
        ["stylus"] = "stylus",
        ["polymer"] = "polymer",
        ["browserify"] = "node",
        ["selenium"] = "test",
        ["aws"] = "aws",
        ["google"] = "gcloud",
        ["heroku"] = "hashicorp",
        ["vercel"] = "vercel",
        ["netlify"] = "netlify",
        ["cloudflare"] = "cloudflare",
        ["kubernetes"] = "kubernetes",
        ["k8s"] = "kubernetes",
        ["helm"] = "helm",
        ["github"] = "github",
        ["gitlab"] = "gitlab",
        ["bitbucket"] = "bitbucketpipeline",
        ["drone"] = "drone",
        ["teamcity"] = "jetbrains",
        ["prometheus"] = "prometheus",
        ["grafana"] = "prometheus",
        ["newrelic"] = "datadog",
        ["firebase"] = "firebase",
        ["typeorm"] = "db",
        ["hibernate"] = "db",
        ["entity"] = "db",
        ["grpc"] = "protobuf",
        ["soap"] = "xml",
        ["cassandra"] = "db",
        ["dynamodb"] = "aws",
        ["sequelize"] = "sequelize",
        ["oauth"] = "key",
        ["jwt"] = "key",
        ["ssl"] = "cert",
        ["tls"] = "cert",
        ["android"] = "android",
        ["ios"] = "ios",
        ["react-native"] = "reactjs",
        ["flutter"] = "flutter",
        ["ionic"] = "ionic",
        ["capacitor"] = "capacitor",
        ["cordova"] = "ionic",
        ["electron"] = "electron",
        ["tauri"] = "tauri",
        ["nwjs"] = "node",
        ["raspberry"] = "raspberry",
        ["esp"] = "arduino",
        ["iot"] = "arduino",
        ["notebook"] = "jupyter",
        ["pandas"] = "python",
        ["scipy"] = "python",
        ["tensorflow"] = "python",
        ["pytorch"] = "python",
        ["keras"] = "python",
        ["spark"] = "apache",
        ["hadoop"] = "apache",
        ["kafka"] = "apache",
        ["flink"] = "apache",
        ["hdfs"] = "apache",
        ["kinesis"] = "aws",
        ["pubsub"] = "google",
        ["rabbitmq"] = "rabbitmq",
        ["activemq"] = "apache",
        ["zeromq"] = "binary",
        ["solr"] = "apache",
        ["algolia"] = "search_result",
        ["memcached"] = "memcached",
        ["varnish"] = "cache",
        ["cloudfront"] = "aws",
        ["akamai"] = "cloudflare",
        ["route53"] = "aws",
        ["smtp"] = "outlook",
        ["imap"] = "outlook",
        ["slack"] = "slack",
        ["discord"] = "discord",
        ["telegram"] = "telegram",
        ["whatsapp"] = "whatsapp",
        ["mattermost"] = "slack",
        ["zoom"] = "video",
        ["teams"] = "microsoft",
        ["meet"] = "google",
        ["twitter"] = "twitter",
        ["facebook"] = "facebook",
        ["instagram"] = "instagram",
        ["linkedin"] = "linkedin",
        ["youtube"] = "youtube",
        ["ga"] = "google",
        ["gtm"] = "google",
        ["mixpanel"] = "analytics",
        ["amplitude"] = "analytics",
        ["segment"] = "analytics",
        ["optimizely"] = "analytics",
        ["vwo"] = "analytics",
        ["ab"] = "analytics",
        ["launchdarkly"] = "feature",
        ["flagsmith"] = "feature",
        ["unleash"] = "feature",
        ["bugsnag"] = "sentry",
        ["rollbar"] = "sentry",
        ["airbrake"] = "sentry",
        ["apm"] = "datadog",
        ["dynatrace"] = "datadog",
        ["pingdom"] = "uptime",
        ["uptimerobot"] = "uptime",
        ["statuspage"] = "status",
        ["splunk"] = "log",
        ["logstash"] = "elastic",
        ["fluentd"] = "elastic",
        ["influxdb"] = "db",
        ["jaeger"] = "opentracing",
        ["zipkin"] = "opentracing",
        ["tempo"] = "grafana",
        ["redoc"] = "swagger",
        ["stoplight"] = "swagger",
        ["soapui"] = "test",
        ["jmeter"] = "test",
        ["locust"] = "python",
        ["k6"] = "test",
        ["owasp"] = "security",
        ["zap"] = "security",
        ["burp"] = "security",
        ["metasploit"] = "security",
        ["nmap"] = "security",
        ["wireshark"] = "security",
        ["forensics"] = "security",
        ["autopsy"] = "security",
        ["volatility"] = "security",
        ["ir"] = "security",
        ["sir"] = "security",
        ["soc"] = "security",
        ["gdpr"] = "security",
        ["hipaa"] = "security",
        ["pci"] = "security",
        ["soc2"] = "security",
        ["iso27001"] = "security",
        ["governance"] = "security",
        ["policy"] = "security",
        ["audit"] = "security",
        ["risk"] = "security",
        ["threat"] = "security",
        ["vulnerability"] = "security",
        ["devsecops"] = "security",
        ["sast"] = "security",
        ["dast"] = "security",
        ["sca"] = "security",
        ["container-security"] = "security",
        ["trivy"] = "trivy",
        ["clair"] = "security",
        ["iac-security"] = "security",
        ["tfsec"] = "security",
        ["checkov"] = "security",
        ["kics"] = "security",
        ["supply-chain"] = "security",
        ["snyk"] = "snyk",
        ["dependabot"] = "dependabot",
        ["renovate"] = "renovate",
        ["secrets"] = "key",
        ["vault"] = "hashicorp",
        ["aws-secrets"] = "aws",
        ["azure-keyvault"] = "azure",
        ["gcp-secret-manager"] = "google",
        ["iam"] = "key",
        ["auth0"] = "key",
        ["okta"] = "key",
        ["cognito"] = "aws",
        ["azure-ad"] = "azure",
        ["cert-manager"] = "cert",
        ["letsencrypt"] = "cert",
        ["acme"] = "cert",
        ["kms"] = "aws",
        ["azure-kms"] = "azure",
        ["gcp-kms"] = "google",
        ["encryption"] = "key",
        ["ssh"] = "key",
        ["restore"] = "backup",
        ["disaster-recovery"] = "backup",
        ["bcp"] = "backup",
        ["drp"] = "backup",
        ["ha"] = "high-availability",
        ["failover"] = "high-availability",
        ["load-balancing"] = "high-availability",
        ["dr"] = "backup",
        ["rto"] = "backup",
        ["rpo"] = "backup",
        ["capacity"] = "planning",
        ["scaling"] = "planning",
        ["performance"] = "performance",
        ["optimization"] = "performance",
        ["tuning"] = "performance",
        ["cost"] = "cost",
        ["finops"] = "cost",
        ["budget"] = "cost",
        ["resources"] = "resources",
        ["quota"] = "resources",
        ["limits"] = "resources",
        ["sla"] = "sla",
        ["slo"] = "sla",
        ["sli"] = "sla",
        ["error-budget"] = "sla",
        ["burn-rate"] = "sla",
        ["incident"] = "incident",
        ["escalation"] = "incident",
        ["on-call"] = "incident",
        ["postmortem"] = "incident",
        ["retrospective"] = "incident",
        ["change"] = "change",
        ["release"] = "release",
        ["deployment"] = "deployment",
        ["version"] = "release",
        ["blue-green"] = "deployment",
        ["canary"] = "deployment",
        ["rolling"] = "deployment",
        ["feature-flag"] = "feature",
        ["toggle"] = "feature",
        ["ab-test"] = "test",
        ["experiment"] = "test",
        ["settings"] = "config",
        ["preferences"] = "config",
        ["environment"] = "environment",
        ["dev"] = "environment",
        ["staging"] = "environment",
        ["prod"] = "environment",
        ["infrastructure"] = "infrastructure",
        ["cloudformation"] = "aws",
        ["arm"] = "azure",
        ["server"] = "server",
        ["instance"] = "server",
        ["vm"] = "server",
        ["container"] = "docker",
        ["pod"] = "kubernetes",
        ["orchestration"] = "kubernetes",
        ["scheduler"] = "kubernetes",
        ["service-mesh"] = "istio",
        ["istio"] = "istio",
        ["linkerd"] = "linkerd",
        ["api-gateway"] = "api",
        ["gateway"] = "api",
        ["load-balancer"] = "load-balancing",
        ["lb"] = "load-balancing",
        ["cdn"] = "cloudflare",
        ["edge"] = "cloudflare",
        ["domain"] = "cloudflare",
        ["waf"] = "security",
        ["firewall"] = "security",
        ["ddos"] = "security",
        ["protection"] = "security",
        ["bot"] = "bot",
        ["crawler"] = "bot",
        ["rate-limit"] = "api",
        ["throttling"] = "api",
        ["api-management"] = "api",
        ["rest"] = "rest",
        ["microservice"] = "microservice",
        ["service"] = "service",
        ["monolith"] = "monolith",
        ["legacy"] = "legacy",
        ["serverless"] = "serverless",
        ["lambda"] = "aws",
        ["functions"] = "azure",
        ["edge-computing"] = "cloudflare",
        ["hybrid"] = "cloud",
        ["multi-cloud"] = "cloud",
        ["multi-region"] = "cloud",
        ["global"] = "cloud",
        ["redundancy"] = "high-availability",
        ["continuity"] = "backup",
        ["compliance"] = "security",
        ["cybersecurity"] = "security",
        ["cicd"] = "cicd",
        ["sre"] = "sre",
        ["reliability"] = "sre",
        ["cloud-native"] = "cloud",
        ["digital"] = "digital",
        ["transformation"] = "digital",
        ["innovation"] = "innovation",
        ["research"] = "research",
        ["strategy"] = "strategy",
        ["planning"] = "planning",
        ["leadership"] = "leadership",
        ["management"] = "management",
        ["culture"] = "culture",
        ["team"] = "team",
        ["learning"] = "learning",
        ["training"] = "training",
        ["development"] = "development",
        ["engineering"] = "engineering",
        ["operations"] = "operations",
        ["ops"] = "operations",
        ["support"] = "support",
        ["help"] = "help",
        ["sales"] = "sales",
        ["marketing"] = "marketing",
        ["finance"] = "finance",
        ["accounting"] = "finance",
        ["hr"] = "hr",
        ["recruiting"] = "hr",
        ["legal"] = "legal",
        ["file"] = "file",
        ["document"] = "file",
        ["data"] = "binary",
        ["script"] = "script",
        ["code"] = "code",
        ["source"] = "source",
    };

    private static Dictionary<string, string>? _extensionToIcon;

    public static Dictionary<string, string> ExtensionToIcon
    {
        get
        {
            if (_extensionToIcon != null)
                return _extensionToIcon;

            _extensionToIcon = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            // Get the Assets folder path
            var assetsPath = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory,
                "Assets");

            if (!Directory.Exists(assetsPath))
            {
                // Fallback to relative path if Assets folder not found in base directory
                assetsPath = Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "..",
                    "..",
                    "..",
                    "Assets");

                if (!Directory.Exists(assetsPath))
                {
                    // If still not found, just use manual overrides
                    _extensionToIcon = new Dictionary<string, string>(ManualOverrides);
                    return _extensionToIcon;
                }
            }

            // Auto-generate mappings from SVG files in Assets folder
            foreach (var svgFile in Directory.GetFiles(assetsPath, "*.svg"))
            {
                var iconName = Path.GetFileNameWithoutExtension(svgFile);

                // Skip folder icons and special icons
                if (iconName.StartsWith("folder_") || 
                    iconName.StartsWith("light_") ||
                    iconName == "root_folder" ||
                    iconName.EndsWith("_opened"))
                {
                    continue;
                }

                // Add direct mapping (extension -> icon name)
                _extensionToIcon[iconName] = iconName;

                // Add common variations
                if (iconName.Length <= 8) // Only for short icon names to avoid false positives
                {
                    _extensionToIcon[iconName] = iconName;
                }
            }

            // Apply manual overrides on top of auto-generated mappings
            foreach (var kvp in ManualOverrides)
            {
                _extensionToIcon[kvp.Key] = kvp.Value;
            }

            return _extensionToIcon;
        }
    }
}